### ISSUE TITLE
Won't work unless I trigger it

### ISSUE THREAD

**Issue by tkalfaoglu** [kurikaesu/userspace-tablet-driver-daemon#51] opened 2022-02-15 07:02 UTC
The device does not work until I do a
$  sudo udevadm trigger
manually after the machine restarts.

Fedora 35, KDE, X11.

**Comment by kurikaesu** [comment] 2022-02-25 00:53
I installed KDE onto my Fedora 35 installation and had no issues.
The udevadm trigger is required after installing the driver the first time but also requires the "plugdev" group to exist and your user to be part of that group.

Closing off this as I can't reproduce the issue. Please feel free to reopen if you have more information.

**Closed by kurikaesu** 2022-02-25 00:53 UTC
